version: 2.1

jobs:
  lint:
    docker:
      - image: cimg/node:18.20.3
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
      - run: npm run lint:html
  test:
    docker:
      - image: cimg/node:18.20.3
    steps:
      - checkout
      - run:
          name: Instalar Mocha y Chai
          command: npm install mocha chai
      - run:
          name: Ejecutar pruebas
          command: npx mocha test/test.js
      - run:    
          name: Notificar a Slack 
          command: |
            curl -X POST -H 'Content-type: application/json' --data '{"text":"Test pasados con éxito."}' $SLACK_WEBHOOK_URL

  deploy:
    docker:
      - image: cimg/node:18.20.3
    steps:
      - checkout
      - run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" -X POST "https://api.render.com/deploy/srv-cpgt1a6ct0pc739vl2v0?key=xSaX_h-ugyA")
          if [ $response -eq 200 ]; then
            echo "Deployment successful"
            curl -X POST -H 'Content-type: application/json' --data '{"text":"Deploy exitoso."}' $SLACK_WEBHOOK_URL
          else
            echo "Deployment failed with HTTP status code $response"
            curl -X POST -H 'Content-type: application/json' --data '{"text":"¡Ha fallado el Deploy!"}' "$SLACK_WEBHOOK_URL"
            exit 1
          fi
      - run:
          name: Instalar Cypress
          command: npm install cypress
      - run:
          name: Ejecutar pruebas de Cypress
          command: npm run cypress:run
      - run:    
          name: Notificar a Slack 
          command: |
            curl -X POST -H 'Content-type: application/json' --data '{"text":"Test en producción pasados con éxito."}' $SLACK_WEBHOOK_URL

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - lint:
          filters:
            branches:
              only: main
      - test:
          requires:
            - lint
          filters:
            branches:
              only: main
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: main
